[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "45caa46f3e76fcc9e2dcc7379867251fd8bfdaea"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "7978bb1ac260920c33081b7223d6e8c553df3e66a4f2dca1963fff7a08954ac9"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+1/CoinUtils.v2.11.3.aarch64-linux-musl-cxx03.tar.gz"
[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "29069c96b8badea75f0363b4a174d8761effe93e"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "48a3be1d9abb1c6b89b15c6356dd4cce1f3d285b32c1633c6384d0cb23c7697b"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+1/CoinUtils.v2.11.3.aarch64-linux-musl-cxx11.tar.gz"
[[CoinUtils]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d48b3a6684337711c93db85b74d7d4f4c7e23430"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "49559a271ba3792452b6c2b5955cc8596adbf20a16c3a214c76d57d327a4783a"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+1/CoinUtils.v2.11.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e9280dfeda3a98447828300abde278b63fd9261"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "80295bdee0fb43666530072122927466bd9e97b0e3c6319570ed31b311ae93ef"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+1/CoinUtils.v2.11.3.x86_64-w64-mingw32-cxx11.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "90cb9772c51b78d041d65d844cd1f85b1fa0006d"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "6fc951a9c9a5e3f8eb57d9eaeeb86994e8edcbc95fb735fb2539f16499580945"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+1/CoinUtils.v2.11.3.i686-linux-musl-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e33167eebbf737b0bd035d6786596d40cd1745b"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "ee377a079fd1b416760428a7867c3cf39d67225f3abcff36ec1b2ed37dfbee23"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+1/CoinUtils.v2.11.3.x86_64-linux-musl-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "18f277b66ced4c68d287d958aad3f55077b67001"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "d0c1168e0e8b9f344a38b09a867252020eeb39312c6ac75a0b42a7f49c1e62ae"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+1/CoinUtils.v2.11.3.x86_64-linux-gnu-cxx03.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e020853323aa2734674c2e34bdd5202b481f8fd4"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "1dd9461792a955de1d348731ce7cfd2b3f8585f35ae7056b6464722f57ac471b"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+1/CoinUtils.v2.11.3.i686-linux-gnu-cxx03.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c2860c3446eb961abc0fba96081eddb8e12c9510"
os = "macos"

    [[CoinUtils.download]]
    sha256 = "d62979f56e268b9fef567f71b50416fdce1c8cdb18ab9c1612f842e89b8d6658"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+1/CoinUtils.v2.11.3.x86_64-apple-darwin14-cxx11.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4941010822548e66b855bc62ab2d2063b76e4e57"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "dad56e90db32f11a45d1390de9d08fe92276f383eb1c40a3656a7d53fbe9fe6b"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+1/CoinUtils.v2.11.3.i686-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c097c5a4e4610423955e9219425622ac21f6a60a"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "e6dc4bc952636ec6fea17d31dbc5e38f860a275c238cbb6caf6cfdb933637a04"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+1/CoinUtils.v2.11.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1f22c4442d657e81bccd1bfa100b182a8786ccb7"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "10632159a464e324051c04a66f0f0847bf8da1de50b1dbe5d1ceea801e988510"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+1/CoinUtils.v2.11.3.x86_64-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a054bebdaad5c0b1e9dfa9e64b74891720ca998d"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "450be8e804699021a50cf27849b15f6185936682824521efce0172ddb4a61532"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+1/CoinUtils.v2.11.3.aarch64-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c505f61d1e2428cbe606363b3006fefa2c51b78a"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "232af28c3e407f345125cda3a5d44e05dc8c3489cae171b169fe0ba55b3851f5"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+1/CoinUtils.v2.11.3.x86_64-linux-musl-cxx03.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d1c0d08df25bf229ce24d7e67d1b2533b2e3461e"
os = "macos"

    [[CoinUtils.download]]
    sha256 = "c0f295d1643c03eb990bf0d6b1ab13adc1ddede69d8f0e5e85e030e237868468"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+1/CoinUtils.v2.11.3.x86_64-apple-darwin14-cxx03.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e8781b6bdf3785c44d2909c32983f89c442a8d27"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "5f8977a3927520154ac013a64cb314f6850549e7ca996e2953de012f48ebaa67"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+1/CoinUtils.v2.11.3.i686-w64-mingw32-cxx03.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "19c686410d10ff82e3059f7fa5d1017b3b0078af"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "2f14b7a3e531f3dd45e173e61593d3232da1bf33c28b41b5011d1412b65600c0"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+1/CoinUtils.v2.11.3.i686-w64-mingw32-cxx11.tar.gz"
[[CoinUtils]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a7da23fa11de40c9c7c89b430f832ebb8a3d8038"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "c5e6712c6088a8d838124f3b0984fbd03faf35fad5f0d980b262388b80044530"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+1/CoinUtils.v2.11.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[CoinUtils]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5accddfc1cfc43a029112f873fd47c647845405b"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "161aa41866b7f43dc5451a45562ce00e248c1bcac9fed9bfaac2c517764fba17"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+1/CoinUtils.v2.11.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ebe79dd7f746ae3f92ab80df99bcf4132b8c541a"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "38e934b5dd45aeafb21e8918747c31ecfb178bd1c1723ea0d5df1abfa70e7805"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+1/CoinUtils.v2.11.3.aarch64-linux-gnu-cxx03.tar.gz"
[[CoinUtils]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e66d8181c4bd4ff621944ef6e9f4e07acf2c4f9"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "c012f0bc41e529df4454b84a005263fb955cee68c5f6bd1636c0973062dc81b4"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+1/CoinUtils.v2.11.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fd0f48ad52b8d96f03e17cfbb22d2b732fd73b7b"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "84a7f2cdceefd17e0f10ae4ff1a045ca1dbd14657855131b6e3ca68b69fd126d"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+1/CoinUtils.v2.11.3.i686-linux-musl-cxx03.tar.gz"
