[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c86449e6bee7cdb069be12fad871b63ec595c332"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "8f89b1f55d259e6520ca36234bd5205d2aa5766e4749337d2f9441e7a7c414f6"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+4/CoinUtils.v2.11.3.aarch64-linux-gnu-cxx03.tar.gz"
[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7b1e4aec2a4456be0db6bca26940de824cd1d037"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "ab4040811d7e0cf726a39e8602ae746f060b4334e1a147d5f57c982e750de9e6"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+4/CoinUtils.v2.11.3.aarch64-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "adbc5dedac08ad5744cf0576d7b0a0ebca797531"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "f4870e22a38e4d0554c949bcbf5f403023d4ef7846f6bb87761e3f2bc8d1c0ae"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+4/CoinUtils.v2.11.3.aarch64-linux-musl-cxx03.tar.gz"
[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ff3559abae5db87cfbc988e388f55e3ae30dd61"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "af52deec30fb2b68478c1c3abf6384965911ea6d2539b85328a18e6b5bc72107"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+4/CoinUtils.v2.11.3.aarch64-linux-musl-cxx11.tar.gz"
[[CoinUtils]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dbc4717d6cbc4d7b0ab5d7f7f7abd70e626674a9"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "15db90fdbf7b4f857192909a3c20bbc467c04893bf2766726e3d1d451e0e42c1"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+4/CoinUtils.v2.11.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[CoinUtils]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "918cde80c4b67338ddfee6befeb458765e54042d"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "132ffc8918a151fda3eb479e1c4ad6c9b0304a34858a268516dc6f3f639148c2"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+4/CoinUtils.v2.11.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[CoinUtils]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "60e6911d548b69a77f5afff740adf0809a40f11d"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "1267b4a387451990b36df78f6795ce055d2c071d7c15d7645fde72441bda29de"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+4/CoinUtils.v2.11.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[CoinUtils]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d028c3c730cd67b9df9ac9dfff074f16d3705cd9"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "6c97d87b0662c4998feef6119845fefae215a83a2b150e1e705c8c62f177991a"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+4/CoinUtils.v2.11.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0af3517b921de12804a912bd6d0fdb975572eb93"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "1c060d6bbbc13f8b2930442d0310a7ee670754f205ab9861b95f46ca2c57b881"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+4/CoinUtils.v2.11.3.i686-linux-gnu-cxx03.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "268d4b98afb453ea42470e57164b08eb23800786"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "d8c4b179f9e64e49545711a948715cde0b01ffe72180068bc239a502cc0ba320"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+4/CoinUtils.v2.11.3.i686-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7934a3863a84b5e5fcfde5da526007ea3ca6697c"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "1b1c8b77a41ed6c24d18a750e5871ca81558852c8036d4cbad547ef5d60e158b"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+4/CoinUtils.v2.11.3.i686-linux-musl-cxx03.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5bd596bf88068eeda8fa2d3169cbcc5c4c1407c0"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "8b7df00b93636dbc122def7f58ff59ac1b6976323eb360b859a5dc08da0605c8"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+4/CoinUtils.v2.11.3.i686-linux-musl-cxx11.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6ceb61b4f77811e0e1e25e1c06b6c3f9f345048c"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "a547bc1670d76c89ff4b2192c7068a6d8f890966d335b0cdaf4ab2906727dba4"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+4/CoinUtils.v2.11.3.i686-w64-mingw32-cxx03.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb3ebcae1752b5eaf3ac20aecdb0afa9d761226c"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "14ce77c109a543ec1e15cd8dc80ac816334ad71b1f24d04f5993154630062d57"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+4/CoinUtils.v2.11.3.i686-w64-mingw32-cxx11.tar.gz"
[[CoinUtils]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "596781a489eef7f54f2d7fb7c078ebc41c44b282"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "7f3338b13012af390aee2216df303ca971e7cb3d1e255efb015455fcbe2c9d42"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+4/CoinUtils.v2.11.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[CoinUtils]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "943ebfdaaff0f39c28fc03eb3af5c114848ee3d0"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "c21844163acb882d3824ebc7f81a3e0a8986b74d72a828187aede64337586de0"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+4/CoinUtils.v2.11.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
git-tree-sha1 = "d4c765c280391d07cc373085bda7d702fbcedd51"
os = "macos"

    [[CoinUtils.download]]
    sha256 = "c51dc47752d68535d87e6ba1235d0c2ba154c18317971c9a9a6277937af86e1c"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+4/CoinUtils.v2.11.3.x86_64-apple-darwin.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6d7b810d8767a4dc7330a6b4ade401af9b04094c"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "674b60decc041fb79d7ceed8e3152a4080e3026724fb1d9257a1b1de45aca160"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+4/CoinUtils.v2.11.3.x86_64-linux-gnu-cxx03.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f1c43b95179d3b5c31076267bc1b58718a9ea637"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "1873d57f63ae69ba7b8e9e4f978ea1416dead4d0435d4b5d2e908b47f01a4398"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+4/CoinUtils.v2.11.3.x86_64-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d3fab6e37f80bf29945545a668af4029709e3497"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "d9a742812c1f35742f368cabd7698d7cedea48a69bfa7b0bb29aa1001c6b2f00"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+4/CoinUtils.v2.11.3.x86_64-linux-musl-cxx03.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1bb4c4c04949d909471d880b85e5b4fb1ab95fdb"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "20fdd35f436e56f895fd283c7502a89dabc15337d78e76a9c214bc337b02145f"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+4/CoinUtils.v2.11.3.x86_64-linux-musl-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "620fb9a4b24c3fa7703d846093c9f86ebd4af848"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "15a8a62432da3aacf3daf7c1e64d3837764ac9c5d560e30577b4931eb879b174"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+4/CoinUtils.v2.11.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dea52aacf2bc1168d761bc3ee8b9cd65f9b7b8a7"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "8ee79f535e1bb3938649c52680bb5ba55bcd64ccb455d4b7264fbfc3dc9caa8f"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+4/CoinUtils.v2.11.3.x86_64-w64-mingw32-cxx11.tar.gz"
