[[CoinUtils]]
arch = "aarch64"
git-tree-sha1 = "5fb729719032c86ae2e56addc28e0ae3b7a8e1a8"
os = "macos"

    [[CoinUtils.download]]
    sha256 = "329a8161a48cfbef5610f6cce6c7c0cf81d5f0a946a75fdcbdf1402ea675a014"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1100+0/CoinUtils.v200.1100.1100.aarch64-apple-darwin.tar.gz"
[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "37e4e7b7c64c105ee289499c3305066144496309"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "dd46b7667d98ba26ecd946e3a2f715ccb264bb681e2064dd02cbfc19662089b9"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1100+0/CoinUtils.v200.1100.1100.aarch64-linux-gnu-cxx03.tar.gz"
[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cbcb91a8aae998936832fdb87aadd0a8df252219"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "5b4b759a55912eb3adb957e7515ca03352ab8ab204bef28af366535d601cbee4"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1100+0/CoinUtils.v200.1100.1100.aarch64-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "af55c1ec8e92859986a1b6cf8db11f120e495012"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "a6779f09ab1040c557302f9dd1b0fea647490fefee2326e37b860778ba328bcc"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1100+0/CoinUtils.v200.1100.1100.aarch64-linux-musl-cxx03.tar.gz"
[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fad81cb2824c4be60122a6cf9a47a81af92f2b93"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "26918e1609c2981bcc2b00c79769256f186c6eb473d766d7fad85aba67fe24b5"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1100+0/CoinUtils.v200.1100.1100.aarch64-linux-musl-cxx11.tar.gz"
[[CoinUtils]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dc1eff256ede19e5f464954be482383ec7c1963c"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "f91523763f506875ba0f8a1b0bbce9eec393c4c55b01828b9a5e0143e3b89bd1"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1100+0/CoinUtils.v200.1100.1100.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[CoinUtils]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "21bf1f61cd1315b09e07375d0757f9419a718332"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "685b0ef854116670c08fe947b1d57f5f2a8799a07046372751148e7d301f7d97"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1100+0/CoinUtils.v200.1100.1100.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[CoinUtils]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a63ebee7c4f0b4207a1fad7d458c0b1a0f950757"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "bab6e78eca726bf654875c4732272fd115fe2143de35c4d04965a2a37b669d32"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1100+0/CoinUtils.v200.1100.1100.armv6l-linux-musleabihf-cxx03.tar.gz"
[[CoinUtils]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b79e9f8ff56695fd42b4b92ad7c7d428249d3413"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "4d768932b3526a24d391e0833839244b8e064223506797d9ed219fda868b8567"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1100+0/CoinUtils.v200.1100.1100.armv6l-linux-musleabihf-cxx11.tar.gz"
[[CoinUtils]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9484e3931d7811bf540f06fe68cdb55cf0547fcf"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "cd6126338e75ea3c90d71fa7db264e9360c70abbf605cdab109b1d12b92b3016"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1100+0/CoinUtils.v200.1100.1100.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[CoinUtils]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "04b7fad44aec555253d711504495e7f77d2e07f5"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "99097b6d5fbe5c0e300baedfe6afbada736dbea8dbfa7c56578d5254d7dd0172"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1100+0/CoinUtils.v200.1100.1100.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[CoinUtils]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "23c44337fc5e9b0c127f4566ecdb06d5350ad80f"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "14f564c3987a7d702231114293cad7c33f1e8f38325c13068195bb0628069f62"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1100+0/CoinUtils.v200.1100.1100.armv7l-linux-musleabihf-cxx03.tar.gz"
[[CoinUtils]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ae8a29a37c866dab5cc580393f22957c6f5696e2"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "6bf6210c6cb16a1d93c25883009127622a594b37c4b6a4db616da9717365b1a5"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1100+0/CoinUtils.v200.1100.1100.armv7l-linux-musleabihf-cxx11.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1dd3d6da421f606716aab9158dfd6614cc3f38dd"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "1f7219917d0db1e5a2bf6dcb50b26ac2666caaae1e89178bff54236b9dee949a"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1100+0/CoinUtils.v200.1100.1100.i686-linux-gnu-cxx03.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2990a6eb88639fe3abcd1e31d9ba2c40ebc62314"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "8dc5904ccdf227dd60b902dca740d279690bd9b783f91799d457543f77ca5ecb"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1100+0/CoinUtils.v200.1100.1100.i686-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d9fb8e311d1f488302c4bf1e84cee3cf5faa2cd3"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "a86a0927dd5a404b3e14c4b96c79a4c7baecb60e17ef4c8085b1816228c56d01"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1100+0/CoinUtils.v200.1100.1100.i686-linux-musl-cxx03.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e9b1b5ecac3c2f22bd38fc7214f8517b1a434040"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "fa15eef25abb833f91c02b504afc83e108224e2efe5f21fde5dc5557c22140c3"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1100+0/CoinUtils.v200.1100.1100.i686-linux-musl-cxx11.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9c74138cffbea4966ccb6cf9bb96b64a3b94ce99"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "73853614ae576ac9b944f00efb4bea108af0325bb217b5f95711d6a196d0880d"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1100+0/CoinUtils.v200.1100.1100.i686-w64-mingw32-cxx03.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c556d1f61151b753327868fc678bbecefb193b22"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "8554eccd06d331a02437f7456605d5654116fba5cc48c1d5d1308957962f6964"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1100+0/CoinUtils.v200.1100.1100.i686-w64-mingw32-cxx11.tar.gz"
[[CoinUtils]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "254c3b2bc6b32ffd295eee47e350007261fe1d7e"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "b07a6472ee23be51bbd440fa83f625afa09ea3949902e136cb1c80e9d6744f81"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1100+0/CoinUtils.v200.1100.1100.powerpc64le-linux-gnu-cxx03.tar.gz"
[[CoinUtils]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e2c6511c4cf318b4d02690fb2c3654a085ddc109"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "616dcc7f9d16af735abdfbc01cf69b3f74cd7d4ca2fddac69ef9df523e0ad3f3"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1100+0/CoinUtils.v200.1100.1100.powerpc64le-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
git-tree-sha1 = "89898af753ae1cfcd0b7e30d74b9c8c566721fc0"
os = "macos"

    [[CoinUtils.download]]
    sha256 = "8320564db2b36c9dcbaf934ff4bce6fe44137a3b40ef5d979d3a8f4819e44500"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1100+0/CoinUtils.v200.1100.1100.x86_64-apple-darwin.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dfe81b2abcf37d1360b465b53db2dbaea64c730a"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "3bbaa5fa9e2e99d5cacabd2dec3b16e0856862529b252ee70f0c1b9ad63c871a"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1100+0/CoinUtils.v200.1100.1100.x86_64-linux-gnu-cxx03.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e9f6ca7a737655dcb1f96167a3af43a1e3bc8744"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "e8b4245d1e6e45d3b4ffb8da5d04c10414d85c1f5ecbc1d7a1169dcba0cdd0e2"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1100+0/CoinUtils.v200.1100.1100.x86_64-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "70d232cd0585c78bd298af76ba4ff82252053591"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "45bc00661e8eaba798f2a77421dee370e9c2b027fc8590ab7db1d23ea899e41f"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1100+0/CoinUtils.v200.1100.1100.x86_64-linux-musl-cxx03.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "73da9ca76134094ee9d65fe86ee39c15f9aae7ee"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "5741e89354428f34afd6e765fb8a50e14b457f4790066e4184a700fc411f3113"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1100+0/CoinUtils.v200.1100.1100.x86_64-linux-musl-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "45aeee1400c3cc0588a8420807e458f53ca5fe6b"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "19370932a74a95eb036ccf21a1a4c233d2851c7d657b78c8696ca58df829af86"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1100+0/CoinUtils.v200.1100.1100.x86_64-w64-mingw32-cxx03.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e85eb5bfc3e8922b36f8faec008d17dbd51c8d9d"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "4920819e554a7e5bc15ed0ab0bf4126e37666da77fe48c3e8f97d9720ddc1cd4"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1100+0/CoinUtils.v200.1100.1100.x86_64-w64-mingw32-cxx11.tar.gz"
