[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a462b7266a3b8b2dc59a576945ae65467e0ecdf8"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "dd19e2be97b7c987417036aa9f6584d898995939ecd5e76a8c7d0c5fb0ac761d"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+0/CoinUtils.v2.11.4.aarch64-linux-musl-cxx03.tar.gz"
[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "519e0b051249af139c95257f5f56c239af3d54db"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "8e5d7864cdef641ae21b070f7d064b71b30391e59ebfaba0fe1c08dd24af316f"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+0/CoinUtils.v2.11.4.aarch64-linux-musl-cxx11.tar.gz"
[[CoinUtils]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bc46e1c88976eedebc8525868e1e08a0d0e78e19"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "47b226bee3b52e51b13de70d47320e9ea6bc388a71e959d5a6cdf77910e6a142"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+0/CoinUtils.v2.11.4.armv7l-linux-musleabihf-cxx03.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "948be47683c881327d54f7ff73dddd5eda7a4ad2"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "80d80343791bcfc2ce44cfd58ed19bcd8bb6fe670f88ce4e793fbc3d5e123edb"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+0/CoinUtils.v2.11.4.x86_64-w64-mingw32-cxx11.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cabdb94821f4aa4bb7f2d2884900b57317d9d6c5"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "eb77534374c07e224a287aea20707e3a340fe119f822821f081e8bc808792a95"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+0/CoinUtils.v2.11.4.i686-linux-musl-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb39b507bcdc1929281ab3474d82fd6ce8d4e19e"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "736aa63c3ed342d737a7f332045ebe53d574fb158dfac5a95a1bdf5fdd6d4d12"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+0/CoinUtils.v2.11.4.x86_64-linux-musl-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e27b6b42cad64ddad48786407a78daa8ebd7520d"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "de8bb9a1bca563a1ed383ff547a21d94bb29c803fb583c7e3cc36b94d4207a32"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+0/CoinUtils.v2.11.4.x86_64-linux-gnu-cxx03.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "79d51ac5df17e315ce6dbb351c1da799d334f046"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "3e21fab8085040736ee1f1844baddf02cb33e5d71b0dbafb419ce8a5ab31a7c2"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+0/CoinUtils.v2.11.4.i686-linux-gnu-cxx03.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "38d2a3c2c3ee4e798cb6bf60940d69f19ff59070"
os = "macos"

    [[CoinUtils.download]]
    sha256 = "0be2daf3fe3f9793a4cc352facdedb6b5dfb10cc473387f9f5ea8ef3c71df958"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+0/CoinUtils.v2.11.4.x86_64-apple-darwin14-cxx11.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "80106c608ad307b1beebb37c12c2f63dbb3afd9a"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "87455e66091393ee05003528c96abd2444aff402adcdbfeda26129bceab74e31"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+0/CoinUtils.v2.11.4.i686-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5ef8083d222b43c30c27e654a479110126659872"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "41525933f4d860c907d7804ff10e9f0fc7fcef7318b380e3fdaeade174d0dc63"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+0/CoinUtils.v2.11.4.x86_64-w64-mingw32-cxx03.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aa3a3575e471eeeffbb0e89e09885ce6499f9e62"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "a5a86ee583a718d4e4bdd913b49667ef0413ae2ca1f5b94d15583cab2887c621"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+0/CoinUtils.v2.11.4.x86_64-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ba960969a9461dbbe9edef5bd9f606c9a0f7a1b8"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "481f89333956b8da697efc94f09e1b1027818e6533dabf53cd73408fc2a42a79"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+0/CoinUtils.v2.11.4.aarch64-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dc6d5aa141079f669fc5993aa97e217c6112d430"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "412a26e682ba6c45f8613e80ad0a2c0f881d487cf5eb5dec6b681fdb0fb24a4c"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+0/CoinUtils.v2.11.4.x86_64-linux-musl-cxx03.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5cd381fc20f3db1880b4447ff7c331038d3bcb85"
os = "macos"

    [[CoinUtils.download]]
    sha256 = "20fb5e0b5d91a797d9fe23ad93a8cbafd2f9c5122cfe8929746783f926b911b8"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+0/CoinUtils.v2.11.4.x86_64-apple-darwin14-cxx03.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "961676da012132c50f235735daffc69abd7ca267"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "602f74106d5cb4b28e8a23bf3f943a43a57e24294c447e509e7ac7ed1f473bee"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+0/CoinUtils.v2.11.4.i686-w64-mingw32-cxx03.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d21adefe6e9fa590d13911dc256f097c7ba31c89"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "a2c8f0611f16704a34d62b5632bd22a8a7406089058b2d80f6c6ea81fa6abfbb"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+0/CoinUtils.v2.11.4.i686-w64-mingw32-cxx11.tar.gz"
[[CoinUtils]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c9e0db52aadd99db7e92aa42596e4f639eb58736"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "04676253d8cbca3d986ece5454dbcfcd86918f7565cd4c35a9b4c85e86c860a4"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+0/CoinUtils.v2.11.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[CoinUtils]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "15ed8a6111bb23d0befffdd3b686cff6714cf010"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "6a86d3a4d6ca629a5338412b11b46a0704d1928dd351dec0b97ba5c63557c74e"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+0/CoinUtils.v2.11.4.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e591752f0062369092d57110cec933f408c8ef5a"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "1905d1511233432af5d8716960f351fbac6fab8fa342089084cf7a71a5b811c6"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+0/CoinUtils.v2.11.4.aarch64-linux-gnu-cxx03.tar.gz"
[[CoinUtils]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b075dd59885b0ae30ae8a4baf3936d077cf1755"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "47728611edb6a1e4453b2779933c35202e0d4119b187d1f6a04421ff73a19a85"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+0/CoinUtils.v2.11.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ad54a7be85b7d3b30fa6cd9b3960263555abb066"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "babb5ffe8d0f30f953b5dec09f42e964ce27231598d6fdace5cace91cce1aaba"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+0/CoinUtils.v2.11.4.i686-linux-musl-cxx03.tar.gz"
