[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9c11f21c592b3aabbba5c78eb1a7084523635fe6"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "b397be857cffa42b1e0d68a24a4d388e82c68bf88943f5e162d74b350924842f"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+2/CoinUtils.v2.11.3.aarch64-linux-musl-cxx03.tar.gz"
[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1201e77693f2fa42a4b35f0cfbd0946a91a70553"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "d2c5bda683a28994c570bb95709e25144b5249aac0b6a38c1d99033dc7f58858"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+2/CoinUtils.v2.11.3.aarch64-linux-musl-cxx11.tar.gz"
[[CoinUtils]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b007e379111d4fccaa599760aa2eab76c2776002"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "df024a1162a1881b1e1ba5bef8b668edb218a19afe3b4e7666555b47608f4e0d"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+2/CoinUtils.v2.11.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd993af940ba1e38beb8c5f572027f5a69205ecf"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "a56ea6bab489bd40e9ff13bf61714b34c18c2b739710ffdb74cfe97ebf16a866"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+2/CoinUtils.v2.11.3.x86_64-w64-mingw32-cxx11.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ad578715af22dc3245c05ce28049bac2b49c4756"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "b180fa8261f9a911fce6210d0cc7caeb7a3937fc754cac6409511cee89c9568d"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+2/CoinUtils.v2.11.3.i686-linux-musl-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "284a1376669d27fa5ba3070abaf1b8654b634beb"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "cd10e052e2426c228af4d3cb76f30fd3de97c0c0c6596b5aec0603f98f716b63"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+2/CoinUtils.v2.11.3.x86_64-linux-musl-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "72f6bb0eb03db43d0a7607ce1f2713cde840ba6c"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "b8b9d837d41744e4e246ca0a693feae562eb5b9c0f216f555d0d555a40dbe485"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+2/CoinUtils.v2.11.3.x86_64-linux-gnu-cxx03.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "465a2d6b73f3cad4f8008da9dede46f00d8d9296"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "6ce3f033a2d25c15313640df017bc0cf9eed1b66905a52b5e651ad05bf5970ad"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+2/CoinUtils.v2.11.3.i686-linux-gnu-cxx03.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "655a65698936fd7a86fafa9b34b82c2cff8b01a5"
os = "macos"

    [[CoinUtils.download]]
    sha256 = "429f5c6fc1ab0e2fc5c764e9e3dc2888b2f50d0341bd1c89b6978bfc268bf5af"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+2/CoinUtils.v2.11.3.x86_64-apple-darwin14-cxx11.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a6f4b1c63479b2ee2211648dc66131fe5da3532"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "191ca3d57d2cb16bc350bfffc3ab40768921e76c3784ed05ad4c10e194e0d49f"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+2/CoinUtils.v2.11.3.i686-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d0e2e7522b04f449fc3a6f602415884fc2f8ccd8"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "8c61b7844d4e3cab25195aba244aed4a0f6b13d62fba50607ee71174deb89172"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+2/CoinUtils.v2.11.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0542d9291b18da0bc9fc87295f84033dd59aaf15"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "084895866f69ef916828a87aba824adbd74b1b2b12b1e510d8449efef990391e"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+2/CoinUtils.v2.11.3.x86_64-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "74d524248db5cc52e4c333a652e69cbfe96f594e"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "281d406c299fe4921f526b112bf5c2143740ad622e479d770c61f49dbcd9aa14"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+2/CoinUtils.v2.11.3.aarch64-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e86163c8ae8ad1995f7966604ab0482ecd0b6384"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "cd26b305bb509f2195e53fb808b138e4582058fd073efbccc8a64f459ac15433"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+2/CoinUtils.v2.11.3.x86_64-linux-musl-cxx03.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "433e268ba897190faef72dca99b22ffb8dade925"
os = "macos"

    [[CoinUtils.download]]
    sha256 = "5834f659c246273dea641134febb958f53e76c4fe1f39957dea4f857d5dac60f"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+2/CoinUtils.v2.11.3.x86_64-apple-darwin14-cxx03.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1b212e3b17c1a37c32ee67d6511a256c69fcfed3"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "3a6f3accc91ea61bc06a6eeab172ca56ac696fe2bb2b5b7bb57bdbc529d0bea3"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+2/CoinUtils.v2.11.3.i686-w64-mingw32-cxx03.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "67b168ef3ba077d175a98a3e38193dcb0e5c3c92"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "b645610f3fc9238eb36acd90a1ab9fe6a1b430dd52f762903b976ae04982e140"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+2/CoinUtils.v2.11.3.i686-w64-mingw32-cxx11.tar.gz"
[[CoinUtils]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a06a19c211df82ad8bb8d44698617dea07f3cafd"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "476beb1b75ce5fbbe64bdcfd68b62db113c189a1e66fd2fa5b7d8d85198da018"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+2/CoinUtils.v2.11.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[CoinUtils]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "81253239362749a7ee87700adc0c94cd6e3d52f3"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "1a72e3f85586fe6547c94f1d11eb8ccef7cceeec105ea7c9680ed3106bb45ba1"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+2/CoinUtils.v2.11.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "22f26987361c748a4b76cadb6956f195f219f143"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "bdf03e9d0151b2a36774f50b2ed062809f6c04eb213baeed988a34c3ac86dcdb"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+2/CoinUtils.v2.11.3.aarch64-linux-gnu-cxx03.tar.gz"
[[CoinUtils]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "35c205cb2dbf90b47dd8fe33bc22be1316ead800"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "c99df716b6e04dc9cd0014d7f868f878a6522200dfd13d8599faf41f72f2d5f7"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+2/CoinUtils.v2.11.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1a5a4e62f382b78460dc5728b839c774f4e2f06e"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "83f94924658e648dd0f320eccffc645d7cba32ced25b7b40eaaca671c22dfbc9"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+2/CoinUtils.v2.11.3.i686-linux-musl-cxx03.tar.gz"
