[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5e56cad686d709056c88adee7d2dec408e131b4b"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "1f20e3420c037a0bbeb3e48997fe6ea939f63ed051e87e0af3061c71137f93e8"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+2/CoinUtils.v2.11.4.aarch64-linux-gnu-cxx03.tar.gz"
[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d9076114388444e5a5f2412dac58b8be6b450c38"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "bb015c40e8078ac90bdff10d59908679b79b14fa9b9eba35e487e345dc6bbfc1"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+2/CoinUtils.v2.11.4.aarch64-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "16ddeba598dbe48b13247bada355253f21bb9ab9"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "00147047d6a525580ea95dc626302f2e6735e0804c2dc8ab1bbb578922797d17"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+2/CoinUtils.v2.11.4.aarch64-linux-musl-cxx03.tar.gz"
[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f7a3008710ea3dc32aa139eb8277ab15d9459458"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "1ab59069a30cace4aa00a78cfd91e539221355928fd6efd4f61777ff3cf0ff23"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+2/CoinUtils.v2.11.4.aarch64-linux-musl-cxx11.tar.gz"
[[CoinUtils]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a8e71ff7c1f0a9b593691d16bef20b6bac8ab9ae"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "cc522d99c4b4c299987b14a485306dd50c6f289528ae7ac12318baf81cd7cca1"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+2/CoinUtils.v2.11.4.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[CoinUtils]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f423ed8c8db492194d750299b3f2c561c09f23e"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "a856377026f717daf5551e2310bc12cf36b5fc84903cad26286c16b290b98fd2"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+2/CoinUtils.v2.11.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[CoinUtils]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7d735fc37e762b86fb67ba2327e9cfd082b274d1"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "8827fb46d90d14b84a6983c98842a8bb9ad4fe530f000561d6984058d965416c"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+2/CoinUtils.v2.11.4.armv7l-linux-musleabihf-cxx03.tar.gz"
[[CoinUtils]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bc1e9840cd73860492b3f9f69a67983e2e2d401b"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "84c3603b2853e3080915a467aed7f99ebaa7d48d706be37ae7282a545a7588b0"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+2/CoinUtils.v2.11.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9899a8be9754ea355eedc344f42ffc7e6b139997"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "059de3314ac0c42c6d691947b39c37fd680d2dae948daa247bd6dd2e77028307"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+2/CoinUtils.v2.11.4.i686-linux-gnu-cxx03.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aaea4d63251b8668aff905782841d9f71a109520"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "ed503c452b80365cb77ec04459dd165262eafca1c715e800501f8eb4165da77c"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+2/CoinUtils.v2.11.4.i686-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ad1e34481aaf42ac2ca35a2c22bb02535f4977ad"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "31845ed94a9f926483c91039e9870e4c770c1dc6e465d9686f55c4da925178b6"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+2/CoinUtils.v2.11.4.i686-linux-musl-cxx03.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78f516ff448161b8be4a13a6705689c459a4b8b4"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "039c4bd6a52f10296a8246ef22407176f1b4c42596bbe4cccf5818f2928269a0"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+2/CoinUtils.v2.11.4.i686-linux-musl-cxx11.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2cf203b65978a3eb8eea68c629ae5da873e774dd"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "bcd7c45f4d762beab1d1fdf844c372ce999c70d2759e73a00b624b88f3b03985"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+2/CoinUtils.v2.11.4.i686-w64-mingw32-cxx03.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "51e7e52900fb2a2a3fa2bd7d78e7819aa7c996c5"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "3f9fb455a1241fd5455b09ad470082a15ce37c01f04bc2b01c4cd0d29dd50412"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+2/CoinUtils.v2.11.4.i686-w64-mingw32-cxx11.tar.gz"
[[CoinUtils]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dc90a7f7b8ace6ab60b02449a7f5580f2dada25c"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "972265d73d0bef7a6987f243acf42af352e35f8b5932004bb8bb20d08c7faa67"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+2/CoinUtils.v2.11.4.powerpc64le-linux-gnu-cxx03.tar.gz"
[[CoinUtils]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0814e427a4cd9b795e4822ebc13851f3401558f7"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "da08271a5571f6bf36fec28c28f0be9160724aacfcdb75289a5ba9a1fc5f5dd9"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+2/CoinUtils.v2.11.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
git-tree-sha1 = "42c27cbf64222b540d726665e62953fbb40a2f01"
os = "macos"

    [[CoinUtils.download]]
    sha256 = "828544dd30aaa08d5fc9dde8e5818ad7624d2780ce4412f7d21542933b43f0c5"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+2/CoinUtils.v2.11.4.x86_64-apple-darwin.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e9fffbf402f2c8031c80c536f24e5995a9229430"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "4141e32e5b42e4bc2574871d642215da68006c8a1e59d4edee815b2bcbb90f97"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+2/CoinUtils.v2.11.4.x86_64-linux-gnu-cxx03.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "56a590b5804486f4055019b80686aa574c3a5f13"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "8be86e3158898736bdbb1472fadf25293aca62684c48025243d932d6fedc4aa0"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+2/CoinUtils.v2.11.4.x86_64-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "594cc6ab3452660dd6148bbe47695b2d2c3a9aca"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "62541427aaa1eb50a138af62f7255237dfec0f7e6e7b7a5975877fbb3fce46af"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+2/CoinUtils.v2.11.4.x86_64-linux-musl-cxx03.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d5ec81f82f9536d822fe722be7be2aeb921da124"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "6bb1b54c12b844e1c0541033fc454c9bc8c7d9eb33a519f9b9e744aa213fb4be"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+2/CoinUtils.v2.11.4.x86_64-linux-musl-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "052d83b2beb09d15c2839070bf202086f36047dd"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "3b9aa7b05ad64d069fe80a194589b1136cb74a9d1e0382f133af40fa4d94b019"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+2/CoinUtils.v2.11.4.x86_64-w64-mingw32-cxx03.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "43c12dab3d2f41794afcc693b25413bf433c52b7"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "7ced11f4cfd9b5acd8f3cea0915cc5045b31e8d195d84005599dea92bbada1a9"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.4+2/CoinUtils.v2.11.4.x86_64-w64-mingw32-cxx11.tar.gz"
