[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "71f47ae264da73741651e68b0b147019a3f36178"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "7a22751fe233bf3f0808758617baf129632120346150fc958781f51e8dcb9dbc"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+0/CoinUtils.v2.11.3.aarch64-linux-musl-cxx03.tar.gz"
[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "59adb51941f977b9c1a9e8b860bc28e1122f36a4"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "4b2de03bce3d140dbff73aa11d085d997a5d95c39ed1bd4023e87957d838c18c"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+0/CoinUtils.v2.11.3.aarch64-linux-musl-cxx11.tar.gz"
[[CoinUtils]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "19e86ca4b2f16c20b4d749c13eb49d136b36fab7"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "aca1869918bb2bbdf25073f2decfc99845a092b348d2b2a1379c107e017cca23"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+0/CoinUtils.v2.11.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e6ac574bd7eb799874cde63b69ed2f966b80a02"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "ef779e2f94d35e33832214c68f2c866e1438801d6f60fbd657059e4bb80eed89"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+0/CoinUtils.v2.11.3.x86_64-w64-mingw32-cxx11.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce6588070508b0d1bae8a54c2fbdd81828425278"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "93697910145bbaca41b946e0ec4c91389242f5bfcb2fd2c864cb6613a6da5330"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+0/CoinUtils.v2.11.3.i686-linux-musl-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "33059b5de0324dbacdcec1e45906fe5a57aa7e2a"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "a30e16c931aeb25baaf79b20d0480b5337ef905d023eebd0eff886260189c354"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+0/CoinUtils.v2.11.3.x86_64-linux-musl-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c93ae12411079abed48f94fe0c05193bd514e133"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "05e7209c6263c0ccc7839d46347aa6ca0fcf36b5a75b2e67a8a25868eb7a8ebb"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+0/CoinUtils.v2.11.3.x86_64-linux-gnu-cxx03.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "67917a3192592c73e8de0e022141b56c409d15e7"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "fe9dfb52a941817506165a6517cfc6d02fe9fdccbe47b50061cc3ab81450e8f1"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+0/CoinUtils.v2.11.3.i686-linux-gnu-cxx03.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f662d10d3df910266102aed3e87ca874b876559d"
os = "macos"

    [[CoinUtils.download]]
    sha256 = "69232887bb6b14e8f6d46a71ae511bcf75543b76dcae382868e7a63fdfc26811"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+0/CoinUtils.v2.11.3.x86_64-apple-darwin14-cxx11.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7fb2d4cbc8870ac3cdbebc334a6e4082c36e712e"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "75158e4486717854b78fda8e1d2279c6b8e46a863c120c38d85bc1416c5a2479"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+0/CoinUtils.v2.11.3.i686-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "245c30eda100938daf4e4d681bfaa154d2b61f50"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "6492ab467ed43c590763383f5f1bd7a72b2e79892d4c31af010f980aef08c108"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+0/CoinUtils.v2.11.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8987e9e85144c7f610c7f1be97f2f74f212d94c0"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "210c1ae66bfdf003308c07b01ca01198a207e5973a3b1612f4ce7a7afaadc338"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+0/CoinUtils.v2.11.3.x86_64-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9b6687be67d3845e8ca8430748ab2f09dac8b1d4"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "7958082a821097e66e455b141df2989805e60116644c49678e5892da77b461e9"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+0/CoinUtils.v2.11.3.aarch64-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fa8c66925f43cebeeaa9291226341eb5673d7a98"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "9375820f259757ea6ab922eaa8b6697ddfd4e0cfc65bb3b67ee26ed31016819f"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+0/CoinUtils.v2.11.3.x86_64-linux-musl-cxx03.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "91a72e38d8923b21db4cbe19ff2194d7c895defc"
os = "macos"

    [[CoinUtils.download]]
    sha256 = "2b542269e4fe07693d7428fca947cf655eddd3ad74a65147286f9d72bf22d894"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+0/CoinUtils.v2.11.3.x86_64-apple-darwin14-cxx03.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "26d1267ccb0db257aed199dfec279f1b5fc2ab13"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "ff634c204c0cd7cac293f95d35efab66de3490fc5eaa8dfbaebb1853b207139f"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+0/CoinUtils.v2.11.3.i686-w64-mingw32-cxx03.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f89621e8e8ed2852cb4951dcaffb4e2c29825891"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "23678236d2d1ad465eaa9da9df874b2e0a005ab2191abefd20becbbd32e9c7e0"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+0/CoinUtils.v2.11.3.i686-w64-mingw32-cxx11.tar.gz"
[[CoinUtils]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8506a1fb09dde235f121c1e2eb3bd92301bb1439"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "8c03e0dbd71c019ea115a957ce3018540bb43cecd5111c16f0fbb7e1d48e84fe"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+0/CoinUtils.v2.11.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[CoinUtils]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e01a6b7377ec347a93880c2ebf670bc906add2d3"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "bc0c2e4088d95b578b9dbc8d72531f322c2513e9c016b24e18f24ccbfca76274"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+0/CoinUtils.v2.11.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4b771bdefcdc94087e18a55b2b1e4ffcae713df7"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "72b95659ffce0a710cedcbe0e7addd9a205461cd0591bfbb31c6abdb690d9a1a"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+0/CoinUtils.v2.11.3.aarch64-linux-gnu-cxx03.tar.gz"
[[CoinUtils]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "26889466484f0a271c92cec30459cf880ef20bc9"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "843c055ad8031d1a09b73e3199ba01b142d4be3e73ac36e735d5a9703d0b2362"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+0/CoinUtils.v2.11.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "83352bebb927fd3a9d32e30495a6ca38069eafaa"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "eb58903073d8e72776def906d0f47741453a060803fda742e4af2250970e2897"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+0/CoinUtils.v2.11.3.i686-linux-musl-cxx03.tar.gz"
