[[CoinUtils]]
arch = "aarch64"
git-tree-sha1 = "e1691cf282be92b57d0f92e8e6badbf6611bd25c"
os = "macos"

    [[CoinUtils.download]]
    sha256 = "186d0277ee7b1c80fae3b33a20bfc3d1ccff5a6568576477e8629fa603c9560b"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.600+0/CoinUtils.v200.1100.600.aarch64-apple-darwin.tar.gz"
[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bff627c042a4c506599c0617496898bd35af4a70"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "1156f9535138b6841cbba593f37ab91536e1d0932875521cf819c6cde51b6e1d"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.600+0/CoinUtils.v200.1100.600.aarch64-linux-gnu-cxx03.tar.gz"
[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "edbc7c5eeabb5e7e12cf5bdcdf72727cf6835704"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "c1c57bad09da1e2a7eb954f9ccad805ce2931ee81c2838d98b6b5379e7e52bbf"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.600+0/CoinUtils.v200.1100.600.aarch64-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8ccdaa28911cb4471f42b602d59bbdd76e359869"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "e372381d9187b97e1c4a25b8b99891f3b38e1b52b660795ba9262d126145d14d"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.600+0/CoinUtils.v200.1100.600.aarch64-linux-musl-cxx03.tar.gz"
[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ddb62c555f5f31fee71f358c4d013608fd1341c8"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "9aaa342bc66e985782d384f59357e0d5b611342650fea783740f4d37381cbbb7"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.600+0/CoinUtils.v200.1100.600.aarch64-linux-musl-cxx11.tar.gz"
[[CoinUtils]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2623352ad1ed08d78ea1f33108c26f1e306d951b"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "0c952f45b5d92892220c4d94f62912ebd5b0a2480b35b91ae7bc0ebf8e0ddab9"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.600+0/CoinUtils.v200.1100.600.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[CoinUtils]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "16efffad43464b55921763d29323f4b4807230cd"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "20c05da41bf2deb60c71bf47a07411d007aa14d99b713c09a07d3349bc612f3b"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.600+0/CoinUtils.v200.1100.600.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[CoinUtils]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8ba23ea4ace7398dd315c382509d97ddd3c854a2"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "0cd30e10dc5b33f9b5c499893fa92fad0d949d67983ae3d84ceef762124e96dc"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.600+0/CoinUtils.v200.1100.600.armv6l-linux-musleabihf-cxx03.tar.gz"
[[CoinUtils]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e82036ae6c42ffc1a21f283328e996146fcb6037"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "6572e95681522cd4892030b074cb308b2a3a97706ed0d62bd216921021842806"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.600+0/CoinUtils.v200.1100.600.armv6l-linux-musleabihf-cxx11.tar.gz"
[[CoinUtils]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bb077670185e7bb99f4e6b1dd4d2b80f7b65b575"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "56746e9e667bcad7b5071f73e8425405661913a8c42fb2e02689cbf6c5db945d"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.600+0/CoinUtils.v200.1100.600.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[CoinUtils]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3604928a3f5a71378709d67a71ce85be6f356862"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "655a525775f3af8225dde349a8aa772ad7e9b4375b25de3d26fb39b849140015"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.600+0/CoinUtils.v200.1100.600.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[CoinUtils]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "38a644c85ede5135860c90e862260ed934e84be0"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "c3ec097d2743419e195eec027626fc0c4a187df09a28704eb0e8c78d375ec172"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.600+0/CoinUtils.v200.1100.600.armv7l-linux-musleabihf-cxx03.tar.gz"
[[CoinUtils]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e8e2d3918360f28eafc6332c9f1e8550bdc193b"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "9500d3c052f90c4738e2965bea88f11bf7778b919aa09acbbc69f4aa116c89c6"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.600+0/CoinUtils.v200.1100.600.armv7l-linux-musleabihf-cxx11.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c4d1e7fb56fea64738e3ebe2cc5cd3eec01ecfb5"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "2464673aa9872aba442e7fd4a58be349d501b3468e35971c84e56cae100901a5"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.600+0/CoinUtils.v200.1100.600.i686-linux-gnu-cxx03.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4917047da3343b755c862cd73155dec166d89f1d"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "e9c66f4c138f0d4cdbc26e82f35e940e57f1d6f599428585e3d772f33ab0f009"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.600+0/CoinUtils.v200.1100.600.i686-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "257f0901764dadbe28c71233ab75a7c5efe60178"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "d155b84bdcd7d3721c550f953048d5f14e7a7ae1b1851a3bfc58f6a4ad6d82cd"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.600+0/CoinUtils.v200.1100.600.i686-linux-musl-cxx03.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c8637ee3bca6c39618551278db49ba43f2860c1b"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "40fc207b1cd59b01d1ac716b08e81c65c4c1bb61e66a30103b26475c575496fd"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.600+0/CoinUtils.v200.1100.600.i686-linux-musl-cxx11.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "54457c2b7d826ee781b101d9ef5664976c816b2c"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "a6a7f94cccd34b1f59f449dca9af1db83cd64b3f8ca1365213021b96e17ae050"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.600+0/CoinUtils.v200.1100.600.i686-w64-mingw32-cxx03.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "045d8a7a488fe6335cc901ec3941b6bd611ef797"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "77521849e97773deed84070c3c7f86837b296477b64c41c28a1fcdd28255a13a"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.600+0/CoinUtils.v200.1100.600.i686-w64-mingw32-cxx11.tar.gz"
[[CoinUtils]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ade40f32f8b9895279e864cf858a8cbac27512f1"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "9b164c852875940871b83cf4fa0cdb15893b46faae01ef12a7963f23c80695cb"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.600+0/CoinUtils.v200.1100.600.powerpc64le-linux-gnu-cxx03.tar.gz"
[[CoinUtils]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca3bf4845d205ccaa42b1bcc00d9512db317ee63"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "fb01897a93c6b0d7ec20ed4cb729ef094841840fddb2d4c383ac2802f6717d23"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.600+0/CoinUtils.v200.1100.600.powerpc64le-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
git-tree-sha1 = "6c25776fb219eb3eca8607342c89cb6a629d2057"
os = "macos"

    [[CoinUtils.download]]
    sha256 = "ded26afa321f0b9e39298f7ddbca216fbbd2a800e364db1673d44dfb7187a9ec"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.600+0/CoinUtils.v200.1100.600.x86_64-apple-darwin.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d26e184989645fab70278db7dd477c398d5d6422"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "cba45c3bbe7289e0b883ce990ac28de6f4d2a9e7fdfdb166ed932bdc261ad41b"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.600+0/CoinUtils.v200.1100.600.x86_64-linux-gnu-cxx03.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8d83fe73ba055aad133d3fb55d1f278320d3954f"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "29cd88860fab219c494236af2a2fc95182194990085da9315ad040d28ebefc8b"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.600+0/CoinUtils.v200.1100.600.x86_64-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "70c0e6e0784e84d7330e15a48e7e84a2252a104c"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "c87a9c0b69d8a706082c8e0014bd136e84e817368c8c25f4df9026a8161b126e"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.600+0/CoinUtils.v200.1100.600.x86_64-linux-musl-cxx03.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f7e11d83a166e98f11196057a05f70c8f2c6898b"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "9693d1fb867a328f530f6dc5303fb9aae9f38904334ad3ec88ffce7674c5c886"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.600+0/CoinUtils.v200.1100.600.x86_64-linux-musl-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "31e209909585557812df28ba3a435f9c9f89bab4"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "d1e5cf5786887231ba51cc8ba7474c93e280098cb8816cb21504e73d3ce53949"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.600+0/CoinUtils.v200.1100.600.x86_64-w64-mingw32-cxx03.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dc15757db69e0025bc08cc2c9626efdaa1c3c28d"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "376667f33c00e76ea913549cf3230deb1d4757f312031443e4b4522c5c6b2cf2"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.600+0/CoinUtils.v200.1100.600.x86_64-w64-mingw32-cxx11.tar.gz"
