[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c66fd28b85fc73f623a60873e2777773bb5955ee"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "9f1767793f6cd76eae5883107b4aa54ab66878482e38ccfcfcdc7cd7a28a062b"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+3/CoinUtils.v2.11.3.i686-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "195a89f1e46c8bc58cbda3d63f0b90764ce0409c"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "d823169a6447ddc6d936373dc86bc4df875645dbcb65657dba9d7af56c83aed0"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+3/CoinUtils.v2.11.3.aarch64-linux-musl-cxx03.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f34f3c317443d2a121cbdaa9685fbf508a71f56b"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "554e7188bbe3e2d83e465a2801f8fdeee681c095c5fce83984d6621ea24c3272"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+3/CoinUtils.v2.11.3.i686-w64-mingw32-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "40b865578a50e6a98628169da625f0a6847ba982"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "8a27554528dc05d709eaa5b94a94c42c5bc5e1077397fb95f48e3168c8ea30c8"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+3/CoinUtils.v2.11.3.x86_64-linux-gnu-cxx03.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "38013817fa1341cc1bc8d32a127df3c9f4838da0"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "8d2330b8535ddcf28caa847b646647e3f84d80aed96f52a7d1cc4364395db67b"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+3/CoinUtils.v2.11.3.x86_64-w64-mingw32-cxx11.tar.gz"
[[CoinUtils]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "63d6bd4b8ce2ad120a1cd8416ca97f9f264067b8"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "8047a78733e84130ad4dd35da4c467ac42030ef46f4a68047d911046484695a0"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+3/CoinUtils.v2.11.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[CoinUtils]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "612426288b5206a01c63db8e416e3395b9937b9d"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "9c0ee9d24eebb1ae1d3d9812ef8a4736b33d0b8623242f30629e4b08f967cabc"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+3/CoinUtils.v2.11.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ea6e7d92e60dde083c1a8f8d0b41cd849d23265"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "ec0b4ee688b70b297c37c63a935507a1ea93dae41cb4bf9d96f2e3eceb640070"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+3/CoinUtils.v2.11.3.aarch64-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "69f9a0a1ef01a1716b17c6385094e930ebbe4cac"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "0d66af691ca95b86210752e689ece58dd9180544e0dde40ff577fd391a877faa"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+3/CoinUtils.v2.11.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "053e577fe3163e1a2af10e6d99344eadf6821636"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "72ce86aba09315c4eac242399513e92a60520d25330c4bb5998ee44320b8e3cc"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+3/CoinUtils.v2.11.3.x86_64-linux-musl-cxx11.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "54dc348bd1d62dca92465ed0319658ac034f9099"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "a80db7b2330024284424f898998e9ec1fd101fb45b7c6864d3706bcc2ddbead3"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+3/CoinUtils.v2.11.3.i686-linux-musl-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0ac3456ba92a2df5f79707551be44df7b5cc273b"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "215ca4976c95b01266bbdf540471d7a6fc2dc44f7448b73d2e56dc8aa7a59564"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+3/CoinUtils.v2.11.3.x86_64-linux-musl-cxx03.tar.gz"
[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "27ca422a6a6bcdad7537ea00c5449349a1c73c22"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "a103dd43146ccced68c9488010c0a3515304db2edbbe2e16b65d20c3e8ace177"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+3/CoinUtils.v2.11.3.aarch64-linux-gnu-cxx03.tar.gz"
[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "85214c62ec153ef64fa8fa615ab27851b7655e0f"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "a418cdcaacc7218ea3635e0b1b9b1673e780ab6bd14691a5664c6de4afb50e45"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+3/CoinUtils.v2.11.3.aarch64-linux-musl-cxx11.tar.gz"
[[CoinUtils]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d943299fdede84e1fa5782fee5462e46accee9ee"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "f51af19cc859e2a8cb1b2d6cf2d5f2f06de0eab4a406f1a6b7bb8a58139b3605"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+3/CoinUtils.v2.11.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "139138ae0dcf3770b751edde7ef9bc8154cec958"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "a23ec67fc8e38b39be9ff997ad9491b426a0e18a06029d618b1788a81c473a15"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+3/CoinUtils.v2.11.3.i686-linux-musl-cxx03.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d672735d750b6c4bd6943b8f30b07bbdffc83bad"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "76b2c53477061c965910f5683a793429390a35d1e8b448f1017425a6823b6934"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+3/CoinUtils.v2.11.3.i686-w64-mingw32-cxx03.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4fa1e36ad1d5355fdac79d9315ef08a6200dac10"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "948c1e4fd38d3e112fb4725f51e19b43804de881bb950a3b2cf1728a49c72723"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+3/CoinUtils.v2.11.3.x86_64-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "32ecc811e6b004eb01fb18cf24f3893089415cd7"
os = "macos"

    [[CoinUtils.download]]
    sha256 = "697373d7b3fd30fa6d4e28352be8f74a28f3193d067328957df5112bb7ffe4cc"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+3/CoinUtils.v2.11.3.x86_64-apple-darwin14-cxx03.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "52b73804990d152bf7565afd55e6bcd6afb6efba"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "1e70dca99562b7b434c527a65605f1844610356ed08314c86fb042658def83e3"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+3/CoinUtils.v2.11.3.i686-linux-gnu-cxx03.tar.gz"
[[CoinUtils]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "82802bf38e15469a52bcac63ebdcf7d0c9e83fbc"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "9652a13d44132f0fc774c1ec88b020940accfd44591f064d04f56c183fd2095a"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+3/CoinUtils.v2.11.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d7e1b5d3ffd43be79824a9e74af17b1c8f5d27bd"
os = "macos"

    [[CoinUtils.download]]
    sha256 = "a6a30efe35bd20f57db1363862109979213c7e843a7e9a930b7fb99e00ffb12f"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+3/CoinUtils.v2.11.3.x86_64-apple-darwin14-cxx11.tar.gz"
[[CoinUtils]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aefc372c2e802ed1c8bb8671cc51fde81db9a46e"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "853dd1eb4096374dac83a29cd6f8c3eb6ed00e6fba0aeb8a99120d52f51f9f8a"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+3/CoinUtils.v2.11.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[CoinUtils]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "499af370d18349c6741b74dc99a286ee9fd2dd68"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "9494095f8680320c414daf25fd7122ff47de1263891a7bb529500dd4652d3c3f"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.11.3+3/CoinUtils.v2.11.3.powerpc64le-linux-gnu-cxx03.tar.gz"
