[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e7416c1b6a579afc1058d622ee03301ccddb8da5"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "4e432a2a5d7955b1db4a470315e57212c763ac9f386fb6aa69a999d72d3c922b"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.10.14+1/CoinUtils.v2.10.14.aarch64-linux-musl-cxx03.tar.gz"
[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "667b79d5afe0d713d5904c2da419dd5c3ef3b27b"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "07219109c5ba1ad8a88e395d6bee9f110a056b06cb7829a047320cc7c213a287"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.10.14+1/CoinUtils.v2.10.14.aarch64-linux-musl-cxx11.tar.gz"
[[CoinUtils]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b978066aeeb09746a2a2d7696a388d7e26d2e10e"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "6e12f24876fed3618b64d0e25afb57e77541b4e07f57a47c48afab563c409d1b"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.10.14+1/CoinUtils.v2.10.14.armv7l-linux-musleabihf-cxx03.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9838a82a879d58906c8e42b655c80853312d5af7"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "12628d7553a2274d578a28274a0a653392571575793ba04b617174a0159474a2"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.10.14+1/CoinUtils.v2.10.14.x86_64-w64-mingw32-cxx11.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c5caf1ef71ed07841425b6d8ba0bfb03b6d45e55"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "96578c30a6b79e69dc7b43008280b12b1276954e50f452fcb549a8b70f5a2790"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.10.14+1/CoinUtils.v2.10.14.i686-linux-musl-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0524b68a8cd0c251e4172a9a8a2b78c8ef1ec891"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "ddc8b394739bb07938791c81b5fe0d82a9716b795bdd132dbc05998db281ac69"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.10.14+1/CoinUtils.v2.10.14.x86_64-linux-musl-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c0ed26c549a5a0cdeb18a1966769af248bd03bd2"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "12870a08f5d22966a5a1fae97f11bda992abbaa25082a72447f0b32ca9c08ca1"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.10.14+1/CoinUtils.v2.10.14.x86_64-linux-gnu-cxx03.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cb3fd43ae813d90e98ab1518c9a75e1353abc7ed"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "8fbf516f7c4f15ec43dd0dabd98489814e478fc9548e196238a04b12048591de"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.10.14+1/CoinUtils.v2.10.14.i686-linux-gnu-cxx03.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5d0630463cea1ab5612d29f150bae59bc930afc5"
os = "macos"

    [[CoinUtils.download]]
    sha256 = "193c1115ee91ee892b8a9fc2df2cf1845c035431698eac7e9bf7b7c481165f9d"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.10.14+1/CoinUtils.v2.10.14.x86_64-apple-darwin14-cxx11.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f99a7b72040ce00f879ceb70fff26381374b71b8"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "bddd984c6ac220d079e89a0f3ad0f401127cc5389e0ca0b46a1d34f366445542"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.10.14+1/CoinUtils.v2.10.14.i686-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e1be373462f124360c45b926724d188632d2ec3f"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "9b8b8cadd710786e3614837c20b1a8c8d1c0a08d8807bc330cd26971ad48a287"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.10.14+1/CoinUtils.v2.10.14.x86_64-w64-mingw32-cxx03.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f281373c7a6886a0d38011a0342b7b19bd40ca78"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "cd0ce87f320d8f08cdd1724142cfb1d6fed554f96f0485b82f91446425d416fe"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.10.14+1/CoinUtils.v2.10.14.x86_64-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c55a527e747dc615d22ebfd0dabdeeef262e8797"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "afced1cdb890f697a896da2bd30d22b0ce78ad873bf55fc893936780dd66ec5f"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.10.14+1/CoinUtils.v2.10.14.aarch64-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6e311c4ea08acbea7f9bc03777bddecbd751fe12"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "5d78dea57ddcc59f76f92f0de6aadd996b76afcce2fc8a5a8f329c90be318644"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.10.14+1/CoinUtils.v2.10.14.x86_64-linux-musl-cxx03.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d1be131ae151b1f1a19e02fc1e47df3075446d9d"
os = "macos"

    [[CoinUtils.download]]
    sha256 = "bca72c2d31feb9f6fda9ab65d3e3eb9f338cd8cde030c3c730c9fdd6b8ad2794"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.10.14+1/CoinUtils.v2.10.14.x86_64-apple-darwin14-cxx03.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9013d6020d720c5e05ef38e0d20018f636fcef6e"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "4db4153eeeb07e12ad4d7cd550bbf5e9b3ececdc118f61db1d308c44d5713679"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.10.14+1/CoinUtils.v2.10.14.i686-w64-mingw32-cxx03.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "16cb926d402efba1f56e6584cfe324c6f891b2ec"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "7d8681c0672bbd430b6d245f4ff00853ad2f24939921c98f8f1733a1a373e8d6"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.10.14+1/CoinUtils.v2.10.14.i686-w64-mingw32-cxx11.tar.gz"
[[CoinUtils]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1eb727b47f0cb066568ca555b9b3b1f419578bb4"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "297747fcce3935af4bd84c62da781adc340e52cc9552701bed21f45efcd267da"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.10.14+1/CoinUtils.v2.10.14.armv7l-linux-musleabihf-cxx11.tar.gz"
[[CoinUtils]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "46ec3d0938cb2f7a52646edf9934c389389dea47"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "9b6331919f3b484705a6449cbe7ce6dedccad78e46dd48f2286d4a02e340cad8"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.10.14+1/CoinUtils.v2.10.14.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "272e77b7213e0e53f25383fb09fa91f4a2380886"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "47ae80bf340b70c9fbea88ee216cd69d1977a2a3ec8429cb518efc38fbf097cd"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.10.14+1/CoinUtils.v2.10.14.aarch64-linux-gnu-cxx03.tar.gz"
[[CoinUtils]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2eb068667cd8b3935cde6c0e0f4cfc2b7d26d82b"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "fb0912a036a61fcc32532d6be8267e9b6bb112cd907deab09217e1c1c100062e"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.10.14+1/CoinUtils.v2.10.14.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5a291b6afcc52f8e2ed4c41a543fc3e1f98eec6d"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "17858b1ad218f21dc034d11321ef7e245f5e8a0542b114f8be09e836cdf888a3"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v2.10.14+1/CoinUtils.v2.10.14.i686-linux-musl-cxx03.tar.gz"
