[[CoinUtils]]
arch = "aarch64"
git-tree-sha1 = "25aa7500f1e1b67d58b89e15bffac3f7a38ad1df"
os = "macos"

    [[CoinUtils.download]]
    sha256 = "18665cf36ed9b73f1e340c3559d7a76418b0a46740badee7995865584cbd696a"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1300+0/CoinUtils.v200.1100.1300.aarch64-apple-darwin.tar.gz"
[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "57957926d1924068ff593b9b98cd01823094060c"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "025b09d493ae6b608b09f465bd3e8f79c76f2aebb4678de7e42c28c6aa43c639"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1300+0/CoinUtils.v200.1100.1300.aarch64-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "875371295aa13f6eb299c3bb090ba256d4945ca5"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "f8afcd1cb5611ac43712f4403aa133f21e5c90a87f7d509b9e664a0ecbb959e1"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1300+0/CoinUtils.v200.1100.1300.aarch64-linux-musl-cxx11.tar.gz"
[[CoinUtils]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b4cc6b5133f0afd02dac1bda7954a17cace006d"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "9a30309fa7a297f352badd607513135943b3006781d6e0bf35c72a3bd9de5011"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1300+0/CoinUtils.v200.1100.1300.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[CoinUtils]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "50a571f4740185da68e50ecfc833acc83f8779b6"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "5c465adfed88b9943f9bdafad7ba3471fbd907b01252099c4dd0f29e489a0a2a"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1300+0/CoinUtils.v200.1100.1300.armv6l-linux-musleabihf-cxx11.tar.gz"
[[CoinUtils]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "05f912d20e7da9088697bcaac6961953eb4a80ed"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "18ad3c1041d4af525a99833f7769303850bc35ca58489186e50e25e1e250385b"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1300+0/CoinUtils.v200.1100.1300.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[CoinUtils]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "635a7de93a8ed0de56b6d62afc91b046b6769a3d"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "e0bc9785b9232804b7887e664e87a2611b00886b195d33b1ff4d1f5e1dfe0aaa"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1300+0/CoinUtils.v200.1100.1300.armv7l-linux-musleabihf-cxx11.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "71b37364939dc9b7baa22460647783fbbd7d5612"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "ce03d319db8d02726a1cfff4e605e21ec8e6e7b4c535fee84ba28cbe40fef325"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1300+0/CoinUtils.v200.1100.1300.i686-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f01c7992e7403a756caa065b6a1f621b1f4a464"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "fc90dd779d333f4171625604e05dba5296c6e013c7e8e0571e0c70e1f74416b5"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1300+0/CoinUtils.v200.1100.1300.i686-linux-musl-cxx11.tar.gz"
[[CoinUtils]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ec1cae2aaaca3504873a42dfb5c3e05d5936a215"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "e870beac589b0c51ac394e305c1a655663df2ecf52e4903b3d668b69f737ecc4"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1300+0/CoinUtils.v200.1100.1300.i686-w64-mingw32-cxx11.tar.gz"
[[CoinUtils]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9101c7787b1f383dce0c6f463def1b926e0da80d"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "208dbb856c1a568c854e52d01d2bd18fc43b7ab6b67d28759c39e6c5d6e82c65"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1300+0/CoinUtils.v200.1100.1300.powerpc64le-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
git-tree-sha1 = "6199b96d035cbadb8b5df6b6b598bf65edd4545f"
os = "macos"

    [[CoinUtils.download]]
    sha256 = "2bbcb469274b1ab97523f6793010c759a7b2511b9c0edb2d6111d344991cd010"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1300+0/CoinUtils.v200.1100.1300.x86_64-apple-darwin.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d9a368028804056d457cc5299f2cba9bc633e3d2"
libc = "glibc"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "18c63252cbd5f3bd1993e310e84914352e7282ef900889a3284a791dc1f3a0b1"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1300+0/CoinUtils.v200.1100.1300.x86_64-linux-gnu-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5e9132d14eb4654e3907af43827d62882ea3490b"
libc = "musl"
os = "linux"

    [[CoinUtils.download]]
    sha256 = "d5833ed1a7503daa5dda39bf44ba868489b01064c8ecd1181158c1499755013f"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1300+0/CoinUtils.v200.1100.1300.x86_64-linux-musl-cxx11.tar.gz"
[[CoinUtils]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2c378e98bbe1150c71b3a319b5668caf96ed2b12"
os = "windows"

    [[CoinUtils.download]]
    sha256 = "b7339498ea58deaf657fe38adb20a20824425a9caea5f561dbb976d4606ee161"
    url = "https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases/download/CoinUtils-v200.1100.1300+0/CoinUtils.v200.1100.1300.x86_64-w64-mingw32-cxx11.tar.gz"
